FROM node:12.18.1

WORKDIR /xxx/xxx

COPY ./  ./

# 暴露容器端口
EXPOSE 8080
# 启动node应用
CMD [ "npx", "cross-env", "DEPLOY_ENV=dev", "MIDWAY_SERVER_ENV=dev", "npx", "egg-scripts", "start", "--port=8080", "--title=shenbi", "--framework=@midwayjs/web" ]