// 图片
export default {
  propertyName: 'buttonImage',
  icon: 'pic',
  tag: 'common',
  name: '接口图片',
  containerStyle: {
    bgImgUrl: '',
    position: 'fixed',
    bgColor: 'linear-gradient(90deg, #FF766E 17%, #FF5D3E 83%);',
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    width: 375,
    height: 75,
    paddingTop: 0,
    paddingBottom: 0,
    bottom: 0,
    right: 0,
    left:0,
    align: 'center',
    borderColor: 'rgba(0,0,0,0)',
    borderWidth: 0,
    borderStyle: 'solid',
    borderRadius: 38,
    zIndex: 0,
  },
  selfStyle: {
    width: 335,
    height: 75,
    bgColor: 'linear-gradient(90deg, #FF766E 17%, #FF5D3E 83%);',
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    marginBottom: 0,
    paddingLeft: 0,
    borderColor: 'rgba(0,0,0,0)',
    borderWidth: 0,
    borderStyle: 'solid',
    borderRadius: 38,
  },
  containerStyleReNoOper: ['width', 'left', 'top', 'position'],
  containerStyleAbNoOper: [],
  selfStyleNoOper: [],
  containerAbInitStyle: {
    position: 'absolute', width: 'auto', paddingLeft: 0, paddingRight: 0, marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    marginBottom: 0, paddingTop: 0, paddingBottom: 0, top: 10, left: 10, zIndex: 10
  },
  selfAbInitStyle: { width: 150, height: 150 },
  property: {
    url: 'https://maumkt.ppdaicdn.com/acp/uploadImages/YVKJSC20231129052812.png',
    clickType: 0,
    linkUrl: '',
    toastMsg: '',
    isApi: true,
    apiPath: '/common/userservice/getcustomerqrcodeurl',
    btnURlKey: 'if(res.result===0){window.url=res.resultContent.redirectUrl}else{this.$toast(res.resultMessage)}',
    params: `{"bizLine":"xiaohongshu","scene":"default"}`,
    setAppMarignTop: false, // 用户配置沉浸式导航栏距离顶部导航栏距离,
    animDuration: 1,
    animName: '',
    animCss: '',
    animLoop: false,
    tgtName: '',
    tgtId: '',
    imptgtName: '',
    imptgtId: '',
    page: '',
  }
}
